export const BASE_URL = "http://5.181.217.229:8081";
// export const BASE_URL = "http://localhost:8081";

export const ADD_ARTICLE = "ADD_ARTICLE";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CUTI_SUBMIT = "CUTI_SUBMIT";
export const CUTI_CANCEL_SUBMIT = "CUTI_CANCEL_SUBMIT";
export const CUTI_APPROVE_ATASAN_SUBMIT = "CUTI_APPROVE_ATASAN_SUBMIT";
export const CUTI_APPROVE_PEJABAT_SUBMIT = "CUTI_APPROVE_PEJABAT_SUBMIT";
export const CUTI_LOAD_USER = "CUTI_LOAD_USER";
export const HOLIDAYS_SUBMIT = "HOLIDAYS_SUBMIT";
export const HOLIDAYS_REMOVE = "HOLIDAYS_REMOVE";
export const HOLIDAYS_LOAD = "HOLIDAYS_LOAD";


// response
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";
export const CUTI_SUBMIT_RESPONSE = "CUTI_SUBMIT_RESPONSE";
export const CUTI_LOAD_USER_RESPONSE = "CUTI_LOAD_USER_RESPONSE";
export const CUTI_UPDATE_RESPONSE = "CUTI_UPDATE_RESPONSE";
export const HOLIDAYS_SUBMIT_RESPONSE = "HOLIDAYS_SUBMIT_RESPONSE";
export const HOLIDAYS_REMOVE_RESPONSE = "HOLIDAYS_REMOVE_RESPONSE";
export const HOLIDAYS_LOAD_RESPONSE = "HOLIDAYS_LOAD_RESPONSE";