// export const BASE_URL = "http://5.181.217.229:8081";
export const BASE_URL = "http://localhost:8081/api/v1";

export const POST = 'POST'
export const GET = 'GET'

// request
export const ADD_ARTICLE = "ADD_ARTICLE";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CUTI_SUBMIT = "CUTI_SUBMIT";
export const CUTI_CANCEL_SUBMIT = "CUTI_CANCEL_SUBMIT";
export const CUTI_APPROVE_ATASAN_SUBMIT = "CUTI_APPROVE_ATASAN_SUBMIT";
export const CUTI_APPROVE_PEJABAT_SUBMIT = "CUTI_APPROVE_PEJABAT_SUBMIT";
export const CUTI_LOAD_USER = "CUTI_LOAD_USER";
export const CUTI_DAYS = "CUTI_DAYS";
export const HOLIDAYS_SUBMIT = "HOLIDAYS_SUBMIT";
export const HOLIDAYS_REMOVE = "HOLIDAYS_REMOVE";
export const HOLIDAYS_LOAD = "HOLIDAYS_LOAD";
export const HOLIDAYS_LOAD_FUTURE = "HOLIDAYS_LOAD_FUTURE";

// response
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";
export const CUTI_DAYS_RESPONSE = "CUTI_DAYS_RESPONSE";
export const CUTI_SUBMIT_RESPONSE = "CUTI_SUBMIT_RESPONSE";
export const CUTI_LOAD_USER_RESPONSE = "CUTI_LOAD_USER_RESPONSE";
export const CUTI_UPDATE_RESPONSE = "CUTI_UPDATE_RESPONSE";
export const HOLIDAYS_SUBMIT_RESPONSE = "HOLIDAYS_SUBMIT_RESPONSE";
export const HOLIDAYS_REMOVE_RESPONSE = "HOLIDAYS_REMOVE_RESPONSE";
export const HOLIDAYS_LOAD_RESPONSE = "HOLIDAYS_LOAD_RESPONSE";

// request master doc
export const MASTER_DOCUMENT = "MASTER_DOCUMENT";
export const UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT";
export const USER_DOCUMENT = "USER_DOCUMENT";
export const REMOVE_DOCUMENT = "REMOVE_DOCUMENT";

// response master doc
export const MASTER_DOCUMENT_RESPONSE = "MASTER_DOCUMENT_RESPONSE";
export const UPLOAD_DOCUMENT_RESPONSE = "UPLOAD_DOCUMENT_RESPONSE";
export const USER_DOCUMENT_RESPONSE = "USER_DOCUMENT_RESPONSE";
export const REMOVE_DOCUMENT_RESPONSE = "REMOVE_DOCUMENT_RESPONSE";

// master doc
// request master doc
export const DOCUMENT_PAGE = "DOCUMENT_PAGE";
export const DOCUMENT_CRUD = "DOCUMENT_CRUD";

export const DOCUMENT_PAGE_RESPONSE = "DOCUMENT_PAGE_RESPONSE";
export const DOCUMENT_CRUD_RESPONSE = "DOCUMENT_CRUD_RESPONSE";
