export const BASE_URL = "http://temandawaiditsma.id:8081/api/v1";
// export const BASE_URL = "http://localhost:8081/api/v1";

export const POST = 'POST'
export const GET = 'GET'

// request
export const ADD_ARTICLE = "ADD_ARTICLE";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CUTI_SUBMIT = "CUTI_SUBMIT";
export const CUTI_QUOTA = "CUTI_QUOTA";
export const CUTI_QUOTA_RESPONSE = "CUTI_QUOTA_RESPONSE";
export const CUTI_CANCEL_SUBMIT = "CUTI_CANCEL_SUBMIT";
export const CUTI_CANCEL_SUBMIT_RESPONSE = "CUTI_CANCEL_SUBMIT_RESPONSE";
export const CUTI_APPROVE_ATASAN_SUBMIT = "CUTI_APPROVE_ATASAN_SUBMIT";
export const CUTI_APPROVE_ATASAN_SUBMIT_RESPONSE = "CUTI_APPROVE_ATASAN_SUBMIT_RESPONSE";
export const CUTI_APPROVE_PEJABAT_SUBMIT = "CUTI_APPROVE_PEJABAT_SUBMIT";
export const CUTI_APPROVE_PEJABAT_SUBMIT_RESPONSE = "CUTI_APPROVE_PEJABAT_SUBMIT_RESPONSE";
export const CUTI_LOAD_USER = "CUTI_LOAD_USER";
export const CUTI_DAYS = "CUTI_DAYS";
export const HOLIDAYS_SUBMIT = "HOLIDAYS_SUBMIT";
export const HOLIDAYS_REMOVE = "HOLIDAYS_REMOVE";
export const HOLIDAYS_LOAD = "HOLIDAYS_LOAD";
export const HOLIDAYS_LOAD_FUTURE = "HOLIDAYS_LOAD_FUTURE";
export const HOLIDAYS_LOAD_FUTURE_RESPONSE = "HOLIDAYS_LOAD_FUTURE_RESPONSE";

// response
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";
export const CUTI_DAYS_RESPONSE = "CUTI_DAYS_RESPONSE";
export const CUTI_SUBMIT_RESPONSE = "CUTI_SUBMIT_RESPONSE";
export const CUTI_CALCULATE_DAY = "CUTI_CALCULATE_DAY";
export const CUTI_CALCULATE_DAY_RESPONSE = "CUTI_CALCULATE_DAY_RESPONSE";
export const CUTI_LOAD_USER_RESPONSE = "CUTI_LOAD_USER_RESPONSE";
export const CUTI_UPDATE_RESPONSE = "CUTI_UPDATE_RESPONSE";
export const HOLIDAYS_SUBMIT_RESPONSE = "HOLIDAYS_SUBMIT_RESPONSE";
export const HOLIDAYS_REMOVE_RESPONSE = "HOLIDAYS_REMOVE_RESPONSE";
export const HOLIDAYS_LOAD_RESPONSE = "HOLIDAYS_LOAD_RESPONSE";

// request master doc
export const MASTER_DOCUMENT = "MASTER_DOCUMENT";
export const UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT";
export const USER_DOCUMENT = "USER_DOCUMENT";
export const REMOVE_DOCUMENT = "REMOVE_DOCUMENT";

// response master doc
export const MASTER_DOCUMENT_RESPONSE = "MASTER_DOCUMENT_RESPONSE";
export const UPLOAD_DOCUMENT_RESPONSE = "UPLOAD_DOCUMENT_RESPONSE";
export const USER_DOCUMENT_RESPONSE = "USER_DOCUMENT_RESPONSE";
export const REMOVE_DOCUMENT_RESPONSE = "REMOVE_DOCUMENT_RESPONSE";

// master doc

// request master doc
export const DOCUMENT_LIST = "DOCUMENT_LIST";
export const DOCUMENT_PAGE = "DOCUMENT_PAGE";
export const DOCUMENT_CRUD = "DOCUMENT_CRUD";

export const DOCUMENT_LIST_RESPONSE = "DOCUMENT_LIST_RESPONSE";
export const DOCUMENT_PAGE_RESPONSE = "DOCUMENT_PAGE_RESPONSE";
export const DOCUMENT_CRUD_RESPONSE = "DOCUMENT_CRUD_RESPONSE";

// request master doc
export const JABATAN_LIST = "JABATAN_LIST";
export const JABATAN_PAGE = "JABATAN_PAGE";
export const JABATAN_CRUD = "JABATAN_CRUD";

export const JABATAN_LIST_RESPONSE = "JABATAN_LIST_RESPONSE";
export const JABATAN_PAGE_RESPONSE = "JABATAN_PAGE_RESPONSE";
export const JABATAN_CRUD_RESPONSE = "JABATAN_CRUD_RESPONSE";

// request master duk
export const DUK_LIST = "DUK_LIST";
export const DUK_PAGE = "DUK_PAGE";

export const DUK_LIST_RESPONSE = "DUK_LIST_RESPONSE";
export const DUK_PAGE_RESPONSE = "DUK_PAGE_RESPONSE";

export const DUK_FILTER_PARAM = "DUK_FILTER_PARAM";
export const DUK_FILTER_PARAM_RESPONSE = "DUK_FILTER_PARAM_RESPONSE";

// request master doc
export const PANGKAT_PAGE = "PANGKAT_PAGE";
export const PANGKAT_DOCUMENT_CRUD = "PANGKAT_DOCUMENT_CRUD";

export const PANGKAT_PAGE_RESPONSE = "PANGKAT_PAGE_RESPONSE";
export const PANGKAT_DOCUMENT_CRUD_RESPONSE = "PANGKAT_DOCUMENT_CRUD_RESPONSE";


export const USER = "USER";
export const USER_RESPONSE = "USER_RESPONSE";
export const USER_PAGE = "USER_PAGE";
export const USER_PAGE_RESPONSE = "USER_PAGE_RESPONSE";

export const USER_CRUD = "USER_CRUD";
export const USER_CRUD_RESPONSE = "USER_CRUD_RESPONSE";
export const USER_UPDATE_RESPONSE = "USER_UPDATE_RESPONSE";

export const USER_LIST = "USER_LIST";
export const USER_LIST_RESPONSE = "USER_LIST_RESPONSE";

export const USER_HISTORY_PANGKAT_LIST = "USER_HISTORY_PANGKAT_LIST";
export const USER_HISTORY_PANGKAT_CRUD = "USER_HISTORY_PANGKAT_CRUD";

export const USER_HISTORY_PANGKAT_LIST_RESPONSE = "USER_HISTORY_PANGKAT_LIST_RESPONSE";
export const USER_HISTORY_PANGKAT_CRUD_RESPONSE = "USER_HISTORY_PANGKAT_CRUD_RESPONSE";

export const CUTI_PAGE = "CUTI_PAGE";
export const CUTI_PAGE_RESPONSE = "CUTI_PAGE_RESPONSE";

// dashboard
export const DASHBOARD_JENIS_JABATAN_JENIS_KELAMIN = "DASHBOARD_JENIS_JABATAN_JENIS_KELAMIN"
export const DASHBOARD_JENIS_JABATAN_JENIS_KELAMIN_RESPONSE = "DASHBOARD_JENIS_JABATAN_JENIS_KELAMIN_RESPONSE"

export const DASHBOARD_JABATAN_JENIS_KELAMIN = "DASHBOARD_JABATAN_JENIS_KELAMIN"
export const DASHBOARD_JABATAN_JENIS_KELAMIN_RESPONSE = "DASHBOARD_JABATAN_JENIS_KELAMIN_RESPONSE"

export const DASHBOARD_JABATAN_NAIK_PANGKAT = "DASHBOARD_JABATAN_NAIK_PANGKAT"
export const DASHBOARD_JABATAN_NAIK_PANGKAT_RESPONSE = "DASHBOARD_JABATAN_NAIK_PANGKAT_RESPONSE"

export const DASHBOARD_JABATAN_PENDIDIKAN = "DASHBOARD_JABATAN_PENDIDIKAN"
export const DASHBOARD_JABATAN_PENDIDIKAN_RESPONSE = "DASHBOARD_JABATAN_PENDIDIKAN_RESPONSE"

export const DASHBOARD_JABATAN_USIA = "DASHBOARD_JABATAN_USIA"
export const DASHBOARD_JABATAN_USIA_RESPONSE = "DASHBOARD_JABATAN_USIA_RESPONSE"